### ISSUE TITLE
does the onnxruntime include nms?

### ISSUE THREAD

**Issue by jinfagang** [DefTruth/YOLO5Face.lite.ai.toolkit#1]
does the onnxruntime include nms?

**Comment by DefTruth** [comment]
not in onnxruntime, but include in lite.ai.toolkit, see the source code here:  
* NMS with landmarks in C++: https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/cv/yolo5face.cpp#L162

**Comment by jinfagang** [comment]
@DefTruth is that possible export the model directly with nms baked in?

**Comment by DefTruth** [comment]
> 

一般情况不太可能，也不是很有必要导出NMS。NMS里面的一些for循环，哪怕能导出onnx或其他模型文件，算子也会比较琐碎和冗余。用C++写一个不是很难。

**Comment by jinfagang** [comment]
@DefTruth if target on cpu, it can wrap NonMaxSupression as onnx op. Many forward framework support this op, such as dnn and ort. Not sure about mnn or ncnn

**Comment by DefTruth** [comment]
> @DefTruth if target on cpu, it can wrap NonMaxSupression as onnx op. Many forward framework support this op, such as dnn and ort. Not sure about mnn or ncnn

haha, many thanks for your advice~

**Comment by DefTruth** [comment]
🤔没有很专业地在研究推理引擎，只是平时在做算法研究的时候会业余玩一玩，应用为主哈哈。
